### ISSUE TITLE
SSL error

### ISSUE THREAD

**Issue by mrbub** [phillc73/abettor#1]
Error in function (type, msg, asError = TRUE)  : 
  SSL certificate problem: self signed certificate in certificate chain

loginBF wants to verify SSL certificates with path inputs
Fix:

loginBF2 = function(username, password, applicationKey)
{
credentials <- paste("username=", username, "&password=", password, sep = "")
headersLogin <- list(Accept = "application/json", `X-Application` = applicationKey)
loginReturn <- RCurl::postForm("https://identitysso.betfair.com/api/login", .opts = list(postfields =  credentials, httpheader = headersLogin, ssl.verifypeer = FALSE))
authenticationKey <- jsonlite::fromJSON(loginReturn)
headersPostLogin <- NULL
headersPostLogin <<- list(Accept = "application/json", `X-Application` = authenticationKey$product, 
`X-Authentication` = authenticationKey$token, `Content-Type` = "application/json")
}

just added the ssl verification = FALSE in the RCurl options

**Comment by phillc73** [comment]
Apologies it's taken me so long to address this issue. However, now all functions support the sslVerify parameter (v0.1.3).

At this time, it was easiest and quickest to simply add the sslVerify parameter to all functions, rather than implement a global sslVerify function. The current solution has been tested with all functions and appears to work, but is a little inelegant. You will need to set sslVerify = FALSE as a parameter for all abettor functions, if the SSL verification is failing.

If either mrbub or JJHeathview can confirm this solution fixes the problem, I'll close out the issue.

**Comment by phillc73** [comment]
Assuming fixed, so closing.
