### ISSUE TITLE
Same error everytime

### ISSUE THREAD

**Issue by Eralcar** [phillc73/abettor#20]
Hi 

I am an Italian user of Betfair and I just installed abettor to access Betfair's API. I am currently able to log in to the API using  the Italian API Endpoint but then every time I run a command I get always the same error :
`code   message data.APINGException.requestUUID data.APINGException.errorCode data.APINGException.errorDetails data.exceptionname
1 -32099 ANGX-0007   prdang036-11151112-0006a5fb53               INVALID_APP_KEY                                      APINGException
Warning message:
In listEventTypes() : Error- See output for details`

I really don't know what to do to fix it, I hope you can help me with this issue.
Thank you for your time and consideration

**Comment by phillc73** [comment]
Did you edit the `loginBF()` function to use the Italian endpoint? Currently it just uses the generic endpoint, but it would appear there are special endpoints for Spain and Italy:

http://docs.developer.betfair.com/docs/display/1smk3cen4v3lu3yomq5qye0ni/Betting+On+Italian+Exchange

You'll need to use the Interactive Login - API Endpoint.

If you've already done that, and you're still receiving the error, I don't quite know what to suggest. The error reads like your APP Key is invalid, but that shouldn't be the case if you've successfully logged in. Unfortunately, `abettor` has never before been tested with an Italian account (as far as I am aware). 

Could you try manually walking through one of the functions, piece by piece, after a successful login perhaps? That could help to narrow down where the issue is.

**Comment by Eralcar** [comment]
Hi phill 

Thank you very much for the fast reply, yes I have edited the login function. By the way, I just solved the "problem" which was a simple copy and paste error of the application key, now it is working fine. I will let you know if there are any issues with the italian API. 

Thank you very much for your time.

**Comment by phillc73** [comment]
Good news! Glad you're in. Good luck using Betfair and abettor.
