### ISSUE TITLE
Unable to retrieve any list

### ISSUE THREAD

**Issue by gilesdoy** [phillc73/abettor#25]
Hi, I've received this error when running any of the 'list' commands. Any ideas what the bug might be?

listCompetitions(eventTypeIds=1,
                  toDate = (format(Sys.time() + 86400 * 365, "%Y-%m-%dT%TZ"))
 )
Error in function (type, msg, asError = TRUE)  : 
  error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version

**Comment by JJHeathview** [comment]
Hi Phil,
I get the same error message, the error started on the 2-Dec, do you think it is an issue with my version of RCurl?
Regards,
Jason

________________________________

**Comment by statsgeeknz** [comment]
Hi guys. Maybe due to this (from betfair 18th Nov), which killed our code around the start of Dec:

"Following this announcement from Feb 2019, we are now looking to remove TLS 1.0 support across all other API endpoints.  Specifically, any request to the API that isn’t a Login.
 
Based on our analysis we can see that you are still making requests to the Betfair API using TLS 1.0 from IP address 87.75.176.46
 
We’d like to remove support for TLS 1.0 by Monday 30th November so are notifying you of this so you can make the necessary changes before then."

We've (well, BC, not me) forked this and will send a pull request with changes pretty soon. Might be some other issue you're having though.

**Comment by statsgeeknz** [comment]
Hi guys. Maybe due to this (from betfair 18th Nov), which killed our code around the start of Dec:

"Following this announcement from Feb 2019, we are now looking to remove TLS 1.0 support across all other API endpoints. Specifically, any request to the API that isn’t a Login.

Based on our analysis we can see that you are still making requests to the Betfair API using TLS 1.0 from IP address XXXX

We’d like to remove support for TLS 1.0 by Monday 30th November so are notifying you of this so you can make the necessary changes before then."

We've (well, BC, not me) forked this and will send a pull request with changes pretty soon. Might be some other issue you're having though.

**Comment by statsgeeknz** [comment]
@JJHeathview for the record - sort of yes, so we're getting rid of RCurl in favour of httr. I expect B will have something to say at some point.

**Comment by phillc73** [comment]
Apologies, for the delayed reply, I haven't used this code for such a long time now, so it isn't getting any love.

At one point I did start migrating from RCurl to httr. Then I decided actually, I didn't want to buy into the Tidyverse (yep, Datatable rather than dplyr for me), and was thinking of migrating back to RCurl. In short, the chances of me migrating everything to httr is slim. I'd rather force use of newer RCurl and TSL > 1.0.

Have a look at this [StackOverflow post](https://stackoverflow.com/a/42163908) covering determining the SSL Version of your RCurl and also how to enforce later versions.

E.g.
```
RCurl::curlVersion()$ssl_version
```

Some functions, such as `listCountries()`, `listClearedOrder()` and `listMarketPandL()` were migrated to httr, so it might be worth checking if they still work, when `listCompetitions()`, still on RCurl, doesn't.

If someone would like to submit a PR to cover forcing newer versions of TLS > 1.0 with RCurl, I'd be very pleased to merge it.

Also, having said that, if someone keen and actively using this code would like to be added as a maintainer of this repository I'd also be happy to discuss.

**Comment by gilesdoy** [comment]
Thanks all for the suggestions. I'm a total newbie at all of this so not 100% sure I've completely got this right. But taking `listCompetitions()` as an example, is it as "simple" as converting the code 
`      as.list(jsonlite::fromJSON(
        RCurl::postForm(`
into its httr equivalent
`httr::content(
      httr::POST(`
?

**Comment by jackkelleher** [comment]
@gilesdoy had you any success with your proposed method?

**Comment by gilesdoy** [comment]
It does work, yes, if you recode the relevant parts of `listMarketBook, listCompetitions, listMarketCatalogue and listMarketTypes` into the `httr` structure. Not been able to turn that into a new/separate package though

**Comment by phillc73** [comment]
If you submit a pull request here I will do my best to merge it. If you're not familiar with that, simply paste the enhanced functions into Issue comments and I will integrate them.

**Comment by roseypro** [comment]
Hi all,
 I have attempted to update OpenSSL to version1.1.1a, however RCurl doesn't seem to recognise it. When using `RCurl::curlVersion() ` it shows the version as OpenSSL/1.0.0o. 

When I check the OpenSSL version of the curl package using `curl::curl_version()` it does recognise it. Presumably this means libcurl is pointed at the updated OpenSSL version. Is there a way to point RCurl to the updated OpenSSL?

If not, will try and convert to httr.

Thx, Chris

**Comment by Soccerama** [comment]
Has anyone cracked this yet? I now have working copies on my own machine and would be prepared to try a pull request if there is nothing currently underway.

**Comment by bradley-pearson6597** [comment]
@Soccerama How did you manage to get them working? 
This is the code I devised to try and transfer from RCurl to httr but I'm being thrown a deserialisation error.
`  listMarketBook <- httr::content(
    httr::POST("https://api.betfair.com/exchange/betting/json-rpc/v1",
                               httr::add_headers(headers),
                               httr::content_type_json(),
                               body = list(postfields = listMarketBookOps, 
                                             ssl.verifypeer = sslVerify)
    )
    )`

**Comment by Soccerama** [comment]
Good point - I did it by not using httr.

 

I'm now trying to get httr work.

 

 

Sent: Monday, January 18, 2021 at 4:28 AM

**Comment by Soccerama** [comment]
I've spent some more time on this today and it looks like we are stuck on the same thing. No approach that I've tried gets the output into a dataframe as required.

 

The solution that I have is borrowed from someone else and uses curl  so it is inconsistent with what is done in other functions which is not ideal.


 
 

Sent: Monday, January 18, 2021 at 4:28 AM

**Comment by bradley-pearson6597** [comment]
@Soccerama managed to resolve it.

Here's the code that needs to be changed:
`  listMarketCatalogueOps <- jsonlite::toJSON(jsonlite::unbox(listMarketCatalogueOps))
  product <- Sys.getenv("product")
  token <- Sys.getenv("token")
  listMarketCat <- httr::content(
    httr::POST(url = "https://api.betfair.com/exchange/betting/json-rpc/v1", 
               config = httr::config(ssl_verifypeer = sslVerify),
               body = listMarketCatalogueOps,
               httr::add_headers(Accept = "application/json",
                                 `X-Application` = product,  
                                 `X-Authentication` = token)), as = "text")
  listMarketCat <- jsonlite::fromJSON(listMarketCat)
  if (is.null(listMarketCat$error)) 
    as.data.frame(listMarketCat$result)
  else ({
    if (!suppress) 
      warning("Error- See output for details")
    as.data.frame(listMarketCat$error)
  })`

If you do it like this the output is a nice dataframe which you can then easily manipulate.

**Comment by Soccerama** [comment]
> If you do it like this the output is a nice dataframe which you can then easily manipulate.

Bradley, when I copy your code across it doesn't seem to work for me.

Also, I found listCurrentOrders more difficult to work with - have you tried that one?

**Comment by Soccerama** [comment]
Okay, they're all working now! I will tidy it all up and aim to do a pull request in the next few days.

**Comment by bradley-pearson6597** [comment]
Brilliant! Is the output all good?

**Comment by phillc73** [comment]
Thanks everyone who contributed here and especially @Soccerama . I've merged the pull request. The code all looked like it made sense, but to be completely honest I didn't personally run the code against any API queries. I'm open to more feedback if anyone finds bugs.

There may be some versioning things to take care of. The DESCRIPTION file states `httr (>= 1.4.0)` but it may be that this needs to change.

**Comment by Soccerama** [comment]
Thanks. I did some testing but far from best practice so wouldn't be surprised if there were some issues. 

How do we get a new release so it automatically rolls out to R?

**Comment by phillc73** [comment]
I never packaged this for CRAN, so you should be able to install direct from the GitHub Master Branch with:

```r
# install.packages("devtools")
devtools::install_github("phillc73/abettor")
library("abettor")
```

Let me know if it doesn't work or you have problems.

**Comment by gilesdoy** [comment]
Really appreciate everyone's help in making this work over the last week, apologies I've not been able to help more. Thank you!
