### ISSUE TITLE
How do i retrieve Australian horse Racing markets

### ISSUE THREAD

**Issue by varadarajanvivek** [phillc73/abettor#6]
In listevents

There are no markets for Australian horse racing.

**Comment by phillc73** [comment]
Unfortunately, the library needs to connect to a different API endpoint to support Australian markets. 

See the Betfair documentation at:

https://api.developer.betfair.com/services/webapps/docs/display/1smk3cen4v3lu3yomq5qye0ni/Betting+on+Australian+Events

Currently, this alternative endpoint is not support. However, it should hopefully be a pretty straightforward change to make, it may just take me a little time. If this is important for you, I can try to work on it sooner rather than later.

I'll leave this issue open until the library is updated and Australian markets supported.

**Comment by nichorowitz** [comment]
Has this issue ever been resolved? Looking to get aus greyhound markets with little success so far.

**Comment by Soccerama** [comment]
This issue is stale and can be closed. There is a simple solution:

listEvents(7, marketCountries = "AU")

**Comment by Soccerama** [comment]
Although it doesn't work properly if you don't put in a fromDate.  I suspect this is a timezone issue as when I changed the code to use an earlier default fromDate (current is T-2 hours) it worked properly. Using an earlier default didn't appear to have any negative side effects. Not sure how you want to deal with this PhillC but it is an easy one to fix - either through being more explicit with timezones or through changing default fromDate.

**Comment by Soccerama** [comment]
This issue does relate to timezones and when I put toDate and fromDate into UTC, which is what Betfair expects, this works as intended. Will do a Pull Request for this.

**Comment by phillc73** [comment]
Thanks @Soccerama
